### ISSUE TITLE
Dropped first cw "dit"

### ISSUE THREAD

**Issue by BobW9BF** [w4mmp/MSCC-PW#19]
Have been using MSCC-PW 20220908 with no startup issues save the "unhandled exception" error on clicking the CW/AUDIO tab.  Dismissing the error message resulted in non-problematic function of MSCC-PW ongoing.

However, it has been pointed out that the first "dit" of a cw transmission is fore-shortened, if heard at all.  My call of W9BF is oft repeated to me as M9BF.  Most operators are too polite to correct or do not respond.  But, on air tests with locals sending me recordings show I have a real problem with this issue.  QRS operation has no beneficial effect.

Hoping that this can be fixed.  I know Flex had this issue with PowerSDR.

Bob W9BF

**Comment by w4mmp** [comment]
Hi Bob,
This will never be completely resolved due to the hardware design of the Proficio and/or the Ultimus.  The switch from receive to transmit is relay controlled.  It has been stated many times that these rigs are not 100% QSK capable.  There is a minimum switch time of the relay of 10ms.  Then add in a small amount of overhead processing, the delay is more like in the range of 15ms to 20ms.  Below is an explanation of how CW works with these rigs.

int TX_Hold_Timer(int period, int reset) {
    int status = FALSE;
    static int counter = 0;
  
    if (reset) {
        counter = period * 3;
    }
    else {
        counter--;
        if (counter <= 0) {
            status = TRUE;
        }
    }
    return status;
}

void *Get_Key_Down_Status(void *my_parm) {
    int r = 0;
    static int tx_mode = FALSE;
    int key = FALSE;
    int timer_expired = 0;
    int sleep_time = 1;

    print_time(0);
    fprintf(G_fp_logfile, "[%d] Get_Key_Down_Status called -> In Semi Break-in mode -> Polling for key down.\n",
            line_number++);
    while (G_Get_Key_Down_Status_Thread_Running) {
        if (G_TX_Inhibit == FALSE) {
            r = usbControlMsgIN(CMD_GET_KEY_DOWN, 0, 0, (char*)&G_key, sizeof(G_key));
            if (G_key && r) {
                timer_expired = TX_Hold_Timer(G_TX_Hold, TRUE);
                if (!tx_mode) {
                    Sleep(G_CW_Key_Down_Delay_time);
                    SetModeRxTx(1, 1);
                    SDRcore_recv_send_param(CMD_SET_SPEAKER_MUTE, 1);
                    SDRcore_trans_send_param(CMD_SET_TX_ON, 1);
                    SDRcore_recv_send_param(CMD_SET_TX_ON, 1);
                    Spectrum_Waterfall_send_param(CMD_SET_TX_ON, 1);
                    tx_mode = TRUE;
                    Gui_send_param(CMD_SET_TX_SET_BY_SERVER, tx_mode);
                    sleep_time = 1;
                    print_time(0);
                    fprintf(G_fp_logfile, "[%d] Get_Key_Down_Status. G_key: %d\n",line_number++, G_key);
                }
            } else {
                timer_expired = TX_Hold_Timer(G_TX_Hold, FALSE);
                if (tx_mode) {
                    if (timer_expired) {
                        SetModeRxTx(0, 1);
                        SDRcore_trans_send_param(CMD_SET_TX_ON, 0);
                        SDRcore_recv_send_param(CMD_SET_TX_ON, 0);
                        Spectrum_Waterfall_send_param(CMD_SET_TX_ON, 0);
                        if (G_Speaker_Mute_Status != MUTED) {
                            SDRcore_recv_send_param(CMD_SET_SPEAKER_MUTE, 0);
                        }
                        tx_mode = FALSE;
                        Gui_send_param(CMD_SET_TX_SET_BY_SERVER, tx_mode);
                        sleep_time = 1;
                    }
                }
            }
        } else {
            print_time(0);
            fprintf(G_fp_logfile, "[%d] Get_Key_Down_Status -> G_TX_Inhibit: %d\n", line_number++, G_TX_Inhibit);
        }
        Sleep(sleep_time);
    }
    G_key = 0;
    print_time(0);
    fprintf(G_fp_logfile, "[%d] Get_Key_Down_Status.  key: %d, Normal Exit.\n",
            line_number++, key);
    pthread_exit(NULL);
    return (NULL);
}

Referring to the above code snippet,  when the rig is placed in CW mode, a processing thread is started (Get_Key_Down_Status). It runs in a tight loop of 1ms.  While it is running it polls for a key down state from the rig.  If it receives a key down status from the rig,  the routine places MSCC-PW into transmit mode (SetModeRxTx(1, 1);).  SetModeRxTX places the rig into transmit mode. At this point a CW will be produced but ONLY after the RX/TX relay in the rig has been switched to transmit mode.  This is where the first element clipping occurs.  There absolutely nothing that can be done about that.  It's in the hardware.  So to add up the delay times: 1ms loop time, time to receive the key down state across the USB connection could be up to several milliseconds (3ms) + processing time to signal the transceiver to switch to TX (3ms) + relay switch time (10ms) = ~17ms.  That is the absolute minimum time required to go from key down to CW tone generation.  

Again, operating at high speed keying in conjunction with low hold times just is not a reality.   High speed CW contesting is not something that is really possible with this rig.  For that to happen the rigs would need to be redesigned to use PIN diode switching.  The rigs do produce real time CW as the CW keying performed directly in the rig via attached key and rig firmware.  However QSK operation is not.  The only solution for the clipped first element is to tap the key, wait for a short period of time and then start keying.  (NOTE: When the MSCC-PW PTT button turns RED, things are set to begin keying). The key tap starts the ball rolling.  From there normal keying is possible.  Keying can be performed at any speed up to 30 WPM (or perhaps even faster but I have not tested above 30 WPM).  

I will continue to think about this and determine if there is a method to correct the first element clip, but it is doubtful something will become available.

73,
Ron

**Comment by Bob-TX** [comment]
Ron, I have an idea that may correct or greatly reduce the shortened first dit issue.
I have been able to send over 40 WPM with good quality code so the actual keying is not a problem but the initial switch from receive to transmit and getting that first dit sent is the issue. My word 'element' below means a single dit or dah in CW.
Consider delaying the beginning and ending of EVERY CW dit or dah sent by a fixed amount. As an example, if I assume that the most delay in response is 25ms when switching from receive to transmit and starting that first dit.....then simply delay the first 'key-down' intentionally by 25ms and then when the hand key or keyer ends ANY ELEMENT, start a software timing loop that extends that 'key-up' event by 25ms. All the actions needed to switch from receive to transmit EXCEPT the actual generation of transmitter output would be achieved in the first 25ms delay.  In effect this would cause latency in the CW keying but since the radio doesn't generate its own audio sidetone, the operator would not hear that. The actual length of each element in transmitted CW would be the same, only the start and stop of each element would be delayed by 25ms.
This method would not eliminate the USB timing delay nor the 1ms loop time but it should allow you to compensate for the transmitter switch to TX (3ms) and relay switch time (~17ms). These delays I'm suggesting would apply to every element sent not just the first one.

**Comment by w4mmp** [comment]
Hi Bob,
Interesting idea.  Off the top of my head, this will need to be accomplished in the firmware.  Windows is not a real time operating system and there are no guarantees the timing will be maintained.  

To implement this an accurate timer will need to used to implement the 25ms "lag" time and this can only be accomplished in something that has a deterministic outcome which is a timer in firmware.

73,
Ron

**Comment by w4mmp** [comment]
Hi Bob,
I understand you are satisfied with the current release.  I will close this issue.  Please create a new one if or when other CW issues arise.

**Comment by BobW9BF** [comment]
Very pleased with cw performance with new release.  

Thanks Ron.
